"""
Pytest configuration and fixtures for config tests.
"""

import pytest
from pathlib import Path
import tempfile
import shutil


@pytest.fixture
def temp_repo():
    """Create a temporary repository directory."""
    temp_dir = Path(tempfile.mkdtemp())
    yield temp_dir
    shutil.rmtree(temp_dir)


@pytest.fixture
def sample_python_repo(temp_repo):
    """Create a sample Python repository structure."""
    # Create Python files
    src_dir = temp_repo / "src"
    src_dir.mkdir()
    (src_dir / "main.py").write_text("def main(): pass\n")
    (src_dir / "utils.py").write_text("def helper(): pass\n")
    
    # Create markers
    (temp_repo / "requirements.txt").write_text("pytest\nrequests\n")
    (temp_repo / "pyproject.toml").write_text("[build-system]\nrequires = ['setuptools']\n")
    
    return temp_repo


@pytest.fixture
def sample_rust_repo(temp_repo):
    """Create a sample Rust repository structure."""
    # Create Rust files
    src_dir = temp_repo / "src"
    src_dir.mkdir()
    (src_dir / "main.rs").write_text("fn main() {}\n")
    (src_dir / "lib.rs").write_text("pub fn add(a: i32, b: i32) -> i32 { a + b }\n")
    
    # Create markers
    (temp_repo / "Cargo.toml").write_text("""[package]
name = "test-project"
version = "0.1.0"
edition = "2021"
""")
    (temp_repo / "Cargo.lock").write_text("# This file is automatically generated\n")
    
    return temp_repo


@pytest.fixture
def sample_node_repo(temp_repo):
    """Create a sample Node.js repository structure."""
    # Create JS/TS files
    src_dir = temp_repo / "src"
    src_dir.mkdir()
    (src_dir / "index.ts").write_text("export const hello = () => 'hello';\n")
    (src_dir / "utils.js").writeText("module.exports = { foo: () => {} };\n")
    
    # Create markers
    (temp_repo / "package.json").write_text('''{
  "name": "test-project",
  "version": "1.0.0",
  "scripts": {
    "test": "jest",
    "build": "tsc"
  }
}''')
    (temp_repo / "package-lock.json").write_text('{"lockfileVersion": 2}\n')
    
    return temp_repo


@pytest.fixture
def sample_mixed_repo(temp_repo):
    """Create a sample mixed-language repository structure."""
    # Python backend
    backend_dir = temp_repo / "backend"
    backend_dir.mkdir()
    (backend_dir / "requirements.txt").write_text("fastapi\npytest\n")
    (backend_dir / "main.py").write_text("from fastapi import FastAPI\n")
    
    # Node frontend
    frontend_dir = temp_repo / "frontend"
    frontend_dir.mkdir()
    (frontend_dir / "package.json").write_text('{"name": "frontend", "version": "1.0.0"}')
    (frontend_dir / "index.js").writeText("console.log('hello');\n")
    
    return temp_repo


@pytest.fixture
def sample_review_config():
    """Return a sample review.yaml content."""
    return """
repo:
  language: python
  profile_default: STANDARD

commands:
  test:
    - "pytest -q"
  lint:
    - "ruff check ."
  typecheck:
    - "mypy ."

security:
  dependency_scan:
    - "pip-audit"
  secret_scan:
    - "gitleaks detect"

policy:
  allow_warn_merge: false
  fail_on_warn_over: 10
"""


@pytest.fixture
def sample_review_config_full():
    """Return a full sample review.yaml content with all sections."""
    return """
repo:
  language: mixed
  profile_default: STRICT

commands:
  test:
    - "pytest -q"
    - "cargo test"
  lint:
    - "ruff check ."
    - "cargo clippy"
  typecheck:
    - "mypy ."
  format:
    - "black --check ."
    - "cargo fmt --check"
  build:
    - "cargo build --release"

security:
  dependency_scan:
    - "cargo audit"
    - "pip-audit"
  secret_scan:
    - "gitleaks detect"
  sast_scan:
    - "bandit -r ."

policy:
  allow_warn_merge: false
  fail_on_warn_over: 0
  require_approval: true
  max_review_time_minutes: 60
"""
