"""
Tests for Rust language support - Task 12

Tests Rust detection, command parsing, and configuration handling.
"""

import pytest
from pathlib import Path
import tempfile

from shared.config.language_detector import (
    Language,
    detect_language,
    detect_monorepo_structure,
    get_recommended_commands,
    suggest_review_yaml,
)
from shared.config.command_runner import (
    RustOutputParser,
    ParsedTestResult,
    ParsedLintResult,
    ParsedSecurityResult,
)
from shared.config.review_config import (
    parse_review_yaml,
    load_review_yaml,
    ReviewConfig,
)


class TestRustDetection:
    """Tests for Rust language detection."""
    
    def test_detect_rust_from_cargo_toml(self, tmp_path):
        """Test detecting Rust from Cargo.toml file."""
        cargo_toml = tmp_path / "Cargo.toml"
        cargo_toml.write_text("""
[package]
name = "my-crate"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
""")
        
        result = detect_language(tmp_path)
        assert result.primary_language == Language.RUST
        assert Language.RUST in result.detected_languages
        assert "Cargo.toml" in result.markers_found[Language.RUST]
    
    def test_detect_rust_from_rs_files(self, tmp_path):
        """Test detecting Rust from .rs source files."""
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        (src_dir / "main.rs").write_text("fn main() { println!(\"Hello\"); }")
        (src_dir / "lib.rs").write_text("pub fn add(a: i32, b: i32) -> i32 { a + b }")
        
        result = detect_language(tmp_path)
        assert result.primary_language == Language.RUST
        assert "*.rs" in result.markers_found[Language.RUST]
    
    def test_detect_rust_from_cargo_lock(self, tmp_path):
        """Test detecting Rust from Cargo.lock file."""
        (tmp_path / "Cargo.lock").write_text("""
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "my-crate"
version = "0.1.0"
""")
        
        result = detect_language(tmp_path)
        assert result.primary_language == Language.RUST
        assert "Cargo.lock" in result.markers_found[Language.RUST]


class TestCargoWorkspace:
    """Tests for Cargo workspace detection."""
    
    def test_detect_cargo_workspace(self, tmp_path):
        """Test detecting Cargo workspace structure."""
        cargo_toml = tmp_path / "Cargo.toml"
        cargo_toml.write_text("""
[workspace]
members = ["crate1", "crate2", "crate3"]
resolver = "2"
""")
        
        # Create member directories
        (tmp_path / "crate1").mkdir()
        (tmp_path / "crate2").mkdir()
        (tmp_path / "crate3").mkdir()
        
        result = detect_monorepo_structure(tmp_path)
        assert result.is_monorepo is True
        assert result.workspace_type == "cargo"
        assert "crate1" in result.packages
        assert "crate2" in result.packages
        assert "crate3" in result.packages
        assert result.language_per_package["crate1"] == Language.RUST
    
    def test_detect_cargo_workspace_with_paths(self, tmp_path):
        """Test detecting Cargo workspace with path patterns."""
        cargo_toml = tmp_path / "Cargo.toml"
        cargo_toml.write_text("""
[workspace]
members = ["packages/*", "tools/cli"]
""")
        
        # Create member directories
        packages_dir = tmp_path / "packages"
        packages_dir.mkdir()
        (packages_dir / "core").mkdir()
        (packages_dir / "utils").mkdir()
        
        tools_dir = tmp_path / "tools" / "cli"
        tools_dir.mkdir(parents=True)
        
        result = detect_monorepo_structure(tmp_path)
        assert result.is_monorepo is True
        assert result.workspace_type == "cargo"


class TestRustRecommendedCommands:
    """Tests for Rust recommended commands."""
    
    def test_rust_test_commands(self):
        """Test Rust test command recommendations."""
        cmds = get_recommended_commands(Language.RUST)
        
        assert "cargo test" in cmds["test"][0]
        assert len(cmds["test"]) >= 1
    
    def test_rust_lint_commands(self):
        """Test Rust lint command recommendations."""
        cmds = get_recommended_commands(Language.RUST)
        
        assert "cargo clippy" in cmds["lint"][0]
        assert len(cmds["lint"]) >= 1
    
    def test_rust_typecheck_commands(self):
        """Test Rust typecheck command recommendations (empty for Rust)."""
        cmds = get_recommended_commands(Language.RUST)
        
        # Rust is compiled, no separate typecheck command
        assert cmds["typecheck"] == []
    
    def test_rust_format_commands(self):
        """Test Rust format command recommendations."""
        cmds = get_recommended_commands(Language.RUST)
        
        assert "cargo fmt" in cmds["format"][0]
    
    def test_rust_security_commands(self):
        """Test Rust security command recommendations."""
        cmds = get_recommended_commands(Language.RUST)
        
        assert "cargo audit" in cmds["security"][0]
        assert len(cmds["security"]) >= 1


class TestRustReviewYaml:
    """Tests for Rust review.yaml generation and parsing."""
    
    def test_suggest_rust_review_yaml(self, tmp_path):
        """Test generating review.yaml for Rust project."""
        (tmp_path / "Cargo.toml").write_text("""
[package]
name = "my-crate"
version = "0.1.0"
""")
        
        yaml_content = suggest_review_yaml(tmp_path)
        
        assert "language: rust" in yaml_content
        assert "cargo test" in yaml_content
        assert "cargo clippy" in yaml_content
        assert "cargo audit" in yaml_content
        assert "policy:" in yaml_content
    
    def test_parse_rust_review_yaml(self):
        """Test parsing a Rust review.yaml configuration."""
        yaml_content = """
repo:
  language: rust
  profile_default: STANDARD

commands:
  test:
    - "cargo test"
  lint:
    - "cargo clippy -- -D warnings"
  format:
    - "cargo fmt --check"
  
security:
  dependency_scan:
    - "cargo audit"
"""
        
        config = parse_review_yaml(yaml_content)
        
        assert config.repo.language.value == "rust"
        assert config.repo.profile_default.value == "STANDARD"
        assert "cargo test" in config.commands.test
        assert "cargo clippy -- -D warnings" in config.commands.lint
        # Note: cargo fmt --check is in format section, not lint
        assert "cargo fmt --check" in config.commands.format
        assert "cargo audit" in config.security.dependency_scan


class TestCargoTestParser:
    """Tests for cargo test output parsing."""
    
    def test_parse_cargo_test_success(self):
        """Parse successful cargo test output."""
        output = """
running 3 tests
test tests::test_add ... ok
test tests::test_subtract ... ok
test tests::test_multiply ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
"""
        result = RustOutputParser.parse_cargo_test(output)
        
        assert result.passed == 3
        assert result.failed == 0
        assert result.skipped == 0
        assert result.total == 3
        assert len(result.test_cases) == 3
    
    def test_parse_cargo_test_with_failures(self):
        """Parse cargo test output with failures."""
        output = """
running 4 tests
test tests::test_pass1 ... ok
test tests::test_pass2 ... ok
test tests::test_fail1 ... FAILED
test tests::test_fail2 ... FAILED

test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out
"""
        result = RustOutputParser.parse_cargo_test(output)
        
        assert result.passed == 2
        assert result.failed == 2
        assert result.total == 4
    
    def test_parse_cargo_test_with_ignored(self):
        """Parse cargo test output with ignored tests."""
        output = """
running 5 tests
test tests::test_normal ... ok
test tests::test_slow ... ignored
test tests::test_flaky ... ignored

test result: ok. 2 passed; 0 failed; 2 ignored; 0 measured; 0 filtered out
"""
        result = RustOutputParser.parse_cargo_test(output)
        
        assert result.passed == 2
        assert result.skipped == 2
        assert result.total == 4
    
    def test_parse_cargo_test_multiple_suites(self):
        """Parse cargo test output with multiple test suites."""
        output = """
running 2 tests
test unit::test_one ... ok
test unit::test_two ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

running 1 test
test integration::test_integration ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
"""
        result = RustOutputParser.parse_cargo_test(output)
        
        assert result.passed == 3
        assert result.failed == 0
        assert result.total == 3


class TestCargoClippyParser:
    """Tests for cargo clippy output parsing."""
    
    def test_parse_cargo_clippy_no_warnings(self):
        """Parse cargo clippy output with no warnings."""
        output = """
    Checking my-crate v0.1.0 (/path/to/crate)
    Finished dev [unoptimized + debuginfo] target(s) in 0.5s
"""
        result = RustOutputParser.parse_cargo_clippy(output)
        
        assert result.warnings == 0
        assert result.errors == 0
    
    def test_parse_cargo_clippy_with_warnings(self):
        """Parse cargo clippy output with warnings."""
        output = """
warning: unused variable: `x`
  --> src/main.rs:10:5
   |
10 |     let x = 42;
   |         ^
   |
   = note: `#[warn(unused_variables)]` on by default

warning: this expression borrows a reference that is immediately dereferenced
  --> src/lib.rs:25:10
   |
25 |     foo(&&value);
   |          ^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

    Finished dev [unoptimized + debuginfo] target(s) in 0.5s
"""
        result = RustOutputParser.parse_cargo_clippy(output)
        
        assert result.warnings == 2
        assert result.errors == 0
        assert result.files_affected == 2
        assert len(result.issues) == 2
    
    def test_parse_cargo_clippy_with_errors(self):
        """Parse cargo clippy output with errors."""
        output = """
error: expected one of `!` or `::`, found `}`
  --> src/main.rs:15:1
   |
15 | }
   | ^

error: cannot find macro `printlnx` in this scope
  --> src/main.rs:12:5
   |
12 |     printlnx!("hello");
   |     ^^^^^^^^
"""
        result = RustOutputParser.parse_cargo_clippy(output)
        
        assert result.errors == 2
        assert result.files_affected == 2


class TestCargoAuditParser:
    """Tests for cargo audit output parsing."""
    
    def test_parse_cargo_audit_no_vulnerabilities(self):
        """Parse cargo audit output with no vulnerabilities."""
        output = """
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 500 security advisories (from /home/user/.cargo/advisory-db)
    Scanning Cargo.lock for vulnerabilities (150 crate dependencies)
"""
        result = RustOutputParser.parse_cargo_audit(output)
        
        assert result.vulnerabilities == 0
        assert result.severity_counts == {'low': 0, 'medium': 0, 'high': 0, 'critical': 0}
    
    def test_parse_cargo_audit_with_vulnerabilities(self):
        """Parse cargo audit output with vulnerabilities."""
        output = """
Crate:     serde
Version:   1.0.100
Title:     Deserialization of untrusted data
Date:      2023-01-15
ID:        RUSTSEC-2023-0001
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0001
Severity:  HIGH
Solution:  upgrade to >= 1.0.150

Crate:     regex
Version:   1.5.0
Title:     Regular expression denial of service
Date:      2022-03-08
ID:        RUSTSEC-2022-0012
URL:       https://rustsec.org/advisories/RUSTSEC-2022-0012
Severity:  MEDIUM
Solution:  upgrade to >= 1.5.5
"""
        result = RustOutputParser.parse_cargo_audit(output)
        
        assert result.vulnerabilities == 2
        assert result.severity_counts['high'] == 1
        assert result.severity_counts['medium'] == 1
        assert len(result.findings) == 2
    
    def test_parse_cargo_audit_with_critical(self):
        """Parse cargo audit output with critical vulnerability."""
        output = """
Crate:     openssl
Version:   0.9.0
Title:     Buffer overflow
Date:      2023-06-01
ID:        RUSTSEC-2023-0020
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0020
Severity:  CRITICAL
Solution:  upgrade to >= 0.10.0
"""
        result = RustOutputParser.parse_cargo_audit(output)
        
        assert result.vulnerabilities == 1
        assert result.severity_counts['critical'] == 1


class TestRustWithSampleCargoToml:
    """Tests using a sample Cargo.toml file."""
    
    def test_with_complex_cargo_toml(self, tmp_path):
        """Test with a complex, realistic Cargo.toml."""
        cargo_toml = tmp_path / "Cargo.toml"
        cargo_toml.write_text("""
[package]
name = "openclaw-runner"
version = "0.2.0"
edition = "2021"
authors = ["OpenClaw Team <team@openclaw.io>"]
description = "Task execution runner for OpenClaw"
license = "MIT"
repository = "https://github.com/openclaw/runner"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
chrono = "0.4"
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.11"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "execution"
harness = false

[profile.release]
opt-level = 3
lto = true
""")
        
        # Also create some .rs files
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        (src_dir / "main.rs").write_text("fn main() {}")
        
        result = detect_language(tmp_path)
        assert result.primary_language == Language.RUST
        assert result.confidence == 1.0


class TestRustParserEdgeCases:
    """Edge case tests for Rust parsers."""
    
    def test_parse_empty_test_output(self):
        """Parse empty cargo test output."""
        result = RustOutputParser.parse_cargo_test("")
        
        assert result.passed == 0
        assert result.failed == 0
        assert result.total == 0
    
    def test_parse_empty_clippy_output(self):
        """Parse empty cargo clippy output."""
        result = RustOutputParser.parse_cargo_clippy("")
        
        assert result.warnings == 0
        assert result.errors == 0
    
    def test_parse_empty_audit_output(self):
        """Parse empty cargo audit output."""
        result = RustOutputParser.parse_cargo_audit("")
        
        assert result.vulnerabilities == 0
        assert result.findings == []
    
    def test_parse_test_output_with_doc_tests(self):
        """Parse cargo test output including doc tests."""
        output = """
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests my-crate

running 2 tests
test src/lib.rs - add (line 10) ... ok
test src/lib.rs - subtract (line 20) ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
"""
        result = RustOutputParser.parse_cargo_test(output)
        
        assert result.passed == 2
        assert result.total == 2
