"""
GitHub Label Management for Symphony PR Bridge.

Provides methods for managing PR labels, including adding, removing,
and creating labels with standard OpenClaw labels.
"""

import logging
from typing import List, Optional, Dict, Any
from dataclasses import dataclass

from .client import GitHubClient, GitHubError, GitHubNotFoundError

logger = logging.getLogger(__name__)


@dataclass
class Label:
    """Represents a GitHub label."""
    name: str
    color: str
    description: Optional[str] = None
    id: Optional[int] = None
    url: Optional[str] = None
    default: bool = False
    
    @classmethod
    def from_api_response(cls, data: dict) -> "Label":
        """Create Label from GitHub API response."""
        return cls(
            name=data["name"],
            color=data["color"],
            description=data.get("description"),
            id=data.get("id"),
            url=data.get("url"),
            default=data.get("default", False),
        )


# Standard OpenClaw labels with their colors and descriptions
STANDARD_LABELS: Dict[str, Dict[str, str]] = {
    "openclaw": {
        "color": "0052CC",  # Blue
        "description": "Managed by OpenClaw Orchestration Stack",
    },
    "needs-review": {
        "color": "FBCA04",  # Yellow
        "description": "PR requires review by Symphony",
    },
    "approved": {
        "color": "0E8A16",  # Green
        "description": "PR has been approved by Symphony",
    },
    "changes-requested": {
        "color": "B60205",  # Red
        "description": "Changes requested by Symphony review",
    },
    "symphony-generated": {
        "color": "5319E7",  # Purple
        "description": "PR automatically generated by Symphony",
    },
    "symphony-reviewed": {
        "color": "1D76DB",  # Light blue
        "description": "PR has been reviewed by Symphony",
    },
    "blocked": {
        "color": "000000",  # Black
        "description": "PR is blocked and requires manual intervention",
    },
    "auto-merge": {
        "color": "28A745",  # Success green
        "description": "Approved for automatic merge when checks pass",
    },
}


class LabelManager:
    """Manages GitHub labels for PRs."""
    
    def __init__(self, client: GitHubClient):
        """
        Initialize label manager.
        
        Args:
            client: GitHub API client
        """
        self.client = client
    
    def list_labels(
        self,
        owner: str,
        repo: str,
        per_page: int = 100,
        page: int = 1,
    ) -> List[Label]:
        """
        List all labels in a repository.
        
        Args:
            owner: Repository owner
            repo: Repository name
            per_page: Results per page (max 100)
            page: Page number
            
        Returns:
            List of Labels
        """
        response = self.client._request(
            "GET",
            f"/repos/{owner}/{repo}/labels",
            params={"per_page": per_page, "page": page},
        )
        
        return [Label.from_api_response(label) for label in response]
    
    def get_label(self, owner: str, repo: str, name: str) -> Optional[Label]:
        """
        Get a label by name.
        
        Args:
            owner: Repository owner
            repo: Repository name
            name: Label name
            
        Returns:
            Label if found, None otherwise
        """
        try:
            response = self.client._request(
                "GET",
                f"/repos/{owner}/{repo}/labels/{name}",
            )
            return Label.from_api_response(response)
        except GitHubNotFoundError:
            return None
    
    def create_label(
        self,
        owner: str,
        repo: str,
        name: str,
        color: str,
        description: Optional[str] = None,
    ) -> Label:
        """
        Create a new label in the repository.
        
        Args:
            owner: Repository owner
            repo: Repository name
            name: Label name
            color: Label color (hex without #)
            description: Label description
            
        Returns:
            Created Label
        """
        # Remove # from color if present
        color = color.lstrip("#")
        
        data = {
            "name": name,
            "color": color,
        }
        
        if description:
            data["description"] = description
        
        response = self.client._request(
            "POST",
            f"/repos/{owner}/{repo}/labels",
            json_data=data,
        )
        
        logger.info(f"Created label '{name}' in {owner}/{repo}")
        return Label.from_api_response(response)
    
    def update_label(
        self,
        owner: str,
        repo: str,
        name: str,
        new_name: Optional[str] = None,
        color: Optional[str] = None,
        description: Optional[str] = None,
    ) -> Label:
        """
        Update an existing label.
        
        Args:
            owner: Repository owner
            repo: Repository name
            name: Current label name
            new_name: New label name
            color: New color (hex without #)
            description: New description
            
        Returns:
            Updated Label
        """
        data = {}
        
        if new_name:
            data["name"] = new_name
        if color:
            data["color"] = color.lstrip("#")
        if description is not None:
            data["description"] = description
        
        response = self.client._request(
            "PATCH",
            f"/repos/{owner}/{repo}/labels/{name}",
            json_data=data,
        )
        
        logger.info(f"Updated label '{name}' in {owner}/{repo}")
        return Label.from_api_response(response)
    
    def delete_label(self, owner: str, repo: str, name: str) -> bool:
        """
        Delete a label from the repository.
        
        Args:
            owner: Repository owner
            repo: Repository name
            name: Label name
            
        Returns:
            True if deleted successfully
        """
        try:
            self.client._request(
                "DELETE",
                f"/repos/{owner}/{repo}/labels/{name}",
            )
            logger.info(f"Deleted label '{name}' from {owner}/{repo}")
            return True
        except GitHubNotFoundError:
            logger.warning(f"Label '{name}' not found in {owner}/{repo}")
            return False
    
    def create_label_if_missing(
        self,
        owner: str,
        repo: str,
        name: str,
        color: str,
        description: Optional[str] = None,
    ) -> Label:
        """
        Create a label only if it doesn't exist.
        
        Args:
            owner: Repository owner
            repo: Repository name
            name: Label name
            color: Label color (hex without #)
            description: Label description
            
        Returns:
            Existing or created Label
        """
        existing = self.get_label(owner, repo, name)
        if existing:
            logger.debug(f"Label '{name}' already exists in {owner}/{repo}")
            return existing
        
        return self.create_label(owner, repo, name, color, description)
    
    def add_label(
        self,
        owner: str,
        repo: str,
        pr_number: int,
        label: str,
    ) -> List[str]:
        """
        Add a label to a pull request.
        
        Args:
            owner: Repository owner
            repo: Repository name
            pr_number: PR number
            label: Label name to add
            
        Returns:
            List of current label names on the PR
        """
        response = self.client._request(
            "POST",
            f"/repos/{owner}/{repo}/issues/{pr_number}/labels",
            json_data={"labels": [label]},
        )
        
        labels = [l["name"] for l in response]
        logger.info(f"Added label '{label}' to PR #{pr_number} in {owner}/{repo}")
        return labels
    
    def add_labels(
        self,
        owner: str,
        repo: str,
        pr_number: int,
        labels: List[str],
    ) -> List[str]:
        """
        Add multiple labels to a pull request.
        
        Args:
            owner: Repository owner
            repo: Repository name
            pr_number: PR number
            labels: List of label names to add
            
        Returns:
            List of current label names on the PR
        """
        if not labels:
            return self.list_pr_labels(owner, repo, pr_number)
        
        response = self.client._request(
            "POST",
            f"/repos/{owner}/{repo}/issues/{pr_number}/labels",
            json_data={"labels": labels},
        )
        
        current_labels = [l["name"] for l in response]
        logger.info(f"Added labels {labels} to PR #{pr_number} in {owner}/{repo}")
        return current_labels
    
    def remove_label(
        self,
        owner: str,
        repo: str,
        pr_number: int,
        label: str,
    ) -> List[str]:
        """
        Remove a label from a pull request.
        
        Args:
            owner: Repository owner
            repo: Repository name
            pr_number: PR number
            label: Label name to remove
            
        Returns:
            List of remaining label names on the PR
        """
        try:
            response = self.client._request(
                "DELETE",
                f"/repos/{owner}/{repo}/issues/{pr_number}/labels/{label}",
            )
            
            labels = [l["name"] for l in response]
            logger.info(f"Removed label '{label}' from PR #{pr_number} in {owner}/{repo}")
            return labels
        except GitHubNotFoundError:
            logger.warning(f"Label '{label}' not found on PR #{pr_number}")
            return self.list_pr_labels(owner, repo, pr_number)
    
    def remove_all_labels(
        self,
        owner: str,
        repo: str,
        pr_number: int,
    ) -> bool:
        """
        Remove all labels from a pull request.
        
        Args:
            owner: Repository owner
            repo: Repository name
            pr_number: PR number
            
        Returns:
            True if successful
        """
        self.client._request(
            "DELETE",
            f"/repos/{owner}/{repo}/issues/{pr_number}/labels",
        )
        
        logger.info(f"Removed all labels from PR #{pr_number} in {owner}/{repo}")
        return True
    
    def list_pr_labels(
        self,
        owner: str,
        repo: str,
        pr_number: int,
    ) -> List[str]:
        """
        List all labels on a pull request.
        
        Args:
            owner: Repository owner
            repo: Repository name
            pr_number: PR number
            
        Returns:
            List of label names
        """
        response = self.client._request(
            "GET",
            f"/repos/{owner}/{repo}/issues/{pr_number}/labels",
        )
        
        return [label["name"] for label in response]
    
    def set_labels(
        self,
        owner: str,
        repo: str,
        pr_number: int,
        labels: List[str],
    ) -> List[str]:
        """
        Set exact labels on a PR (removes any existing labels not in the list).
        
        Args:
            owner: Repository owner
            repo: Repository name
            pr_number: PR number
            labels: Exact list of label names to set
            
        Returns:
            List of current label names on the PR
        """
        response = self.client._request(
            "PUT",
            f"/repos/{owner}/{repo}/issues/{pr_number}/labels",
            json_data={"labels": labels},
        )
        
        current_labels = [l["name"] for l in response]
        logger.info(f"Set labels {labels} on PR #{pr_number} in {owner}/{repo}")
        return current_labels
    
    def setup_standard_labels(self, owner: str, repo: str) -> List[Label]:
        """
        Create all standard OpenClaw labels in the repository.
        
        Args:
            owner: Repository owner
            repo: Repository name
            
        Returns:
            List of created/existing Labels
        """
        labels = []
        for name, config in STANDARD_LABELS.items():
            label = self.create_label_if_missing(
                owner,
                repo,
                name,
                config["color"],
                config.get("description"),
            )
            labels.append(label)
        
        logger.info(f"Setup {len(labels)} standard labels in {owner}/{repo}")
        return labels
    
    def has_label(
        self,
        owner: str,
        repo: str,
        pr_number: int,
        label: str,
    ) -> bool:
        """
        Check if a PR has a specific label.
        
        Args:
            owner: Repository owner
            repo: Repository name
            pr_number: PR number
            label: Label name to check
            
        Returns:
            True if PR has the label
        """
        current_labels = self.list_pr_labels(owner, repo, pr_number)
        return label in current_labels
